# Generated by Django 5.1.4 on 2026-08-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('rut', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('tracto_patente', models.CharField(blank=True, max_length=20, null=True)),
                ('modelo_tracto', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=30)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TarifaMaestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=150)),
                ('mandante', models.CharField(blank=True, max_length=150, null=True)),
                ('codigo_local', models.CharField(blank=True, max_length=30, null=True)),
                ('region', models.CharField(blank=True, max_length=30, null=True)),
                ('origen', models.CharField(max_length=150)),
                ('destino', models.CharField(max_length=200)),
                ('ruta', models.CharField(max_length=350)),
                ('tipo_servicio', models.CharField(max_length=30)),
                ('tarifa_neta', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tasa_iva', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
                ('vigente_desde', models.DateField(blank=True, null=True)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(default='Activa', max_length=30)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'tarifa maestra',
                'verbose_name_plural': 'tarifas maestras',
                'ordering': ['destino', 'tipo_servicio'],
            },
        ),
        migrations.CreateModel(
            name='Tracto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=20, unique=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('conductor_asignado', models.CharField(blank=True, max_length=150, null=True)),
                ('rut_conductor', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(default='Disponible', max_length=30)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['patente'],
            },
        ),
    ]
