# Generated by Django 5.1.4 on 2026-08-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='direccion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='dirección / ciudad'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conductor',
            name='tipo_contrato',
            field=models.CharField(blank=True, help_text='Ej: Plazo Fijo, Indefinido.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tracto',
            name='marca',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='tracto',
            name='proveedor_gps',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='tracto',
            name='tag',
            field=models.CharField(blank=True, help_text='Dispositivo de telepeaje.', max_length=60, null=True, verbose_name='TAG'),
        ),
        migrations.AddField(
            model_name='tracto',
            name='tarjeta_combustible',
            field=models.CharField(blank=True, help_text='Ej: Shell Card, Aramco.', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='tracto',
            name='tipo_camion',
            field=models.CharField(blank=True, help_text='Ej: Tracto Blanco, Tracto Rojo, Chasis.', max_length=60, null=True),
        ),
    ]
