# Generated by Django 5.1.4 on 2026-08-13 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_conductor_direccion_conductor_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracto',
            name='conductor_asignado',
        ),
        migrations.RemoveField(
            model_name='tracto',
            name='rut_conductor',
        ),
        migrations.AddField(
            model_name='tracto',
            name='conductor',
            field=models.ForeignKey(blank=True, help_text='Conductor asignado a este tracto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tractos', to='catalogos.conductor'),
        ),
    ]
