# Generated by Django 5.1.4 on 2026-08-13 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_remove_tracto_conductor_asignado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracto',
            name='conductor',
            field=models.OneToOneField(blank=True, help_text='Conductor asignado a este tracto. Cada conductor puede manejar un solo tracto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracto', to='catalogos.conductor'),
        ),
    ]
