# Generated by Django 5.1.4 on 2026-08-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_alter_tracto_conductor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='tipo_contrato',
            field=models.CharField(blank=True, choices=[('Indefinido', 'Indefinido'), ('Plazo Fijo', 'Plazo Fijo'), ('Por Obra o Faena', 'Por Obra o Faena'), ('Honorarios', 'Honorarios')], max_length=30, null=True),
        ),
    ]
