# Generated by Django 5.1.4 on 2026-10-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_alter_conductor_tipo_contrato'),
        ('operaciones', '0002_remove_servicio_tarifa_maestra_servicio_tarifa_ref'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TarifaMaestra',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='modelo_tracto',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='tracto_patente',
        ),
        migrations.AlterField(
            model_name='tracto',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('En servicio', 'En servicio'), ('En mantención', 'En mantención'), ('Fuera de servicio', 'Fuera de servicio')], default='Disponible', max_length=30),
        ),
    ]
