# Generated by Django 5.1.4 on 2026-10-02 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_delete_tarifamaestra_remove_conductor_modelo_tracto_and_more'),
        ('maestros', '0007_remove_tarifa_tipo_tarifa_remove_tarifa_costo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='proveedor',
            field=models.ForeignKey(help_text='Proveedor (transportista) al que pertenece este conductor.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conductores', to='maestros.proveedor'),
        ),
    ]
