# Generated by Django 5.1.4 on 2026-08-10 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'centro de costo',
                'verbose_name_plural': 'centros de costo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=150, verbose_name='razón social')),
                ('giro', models.CharField(blank=True, max_length=150, null=True)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True, verbose_name='dirección')),
                ('contacto_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('contacto_telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('contacto_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ejecutivo_comercial', models.CharField(blank=True, max_length=150, null=True)),
                ('cupo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='comuna')),
            ],
            options={
                'verbose_name': 'comuna',
                'verbose_name_plural': 'comunas',
                'ordering': ['region__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='FormaDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'forma de pago',
                'verbose_name_plural': 'formas de pago',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Menor número = mayor prioridad.')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'prioridad',
                'verbose_name_plural': 'prioridades',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('rut', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('contacto_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('contacto_telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('contacto_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='región')),
            ],
            options={
                'verbose_name': 'región',
                'verbose_name_plural': 'regiones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoRampla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'tipo de rampla',
                'verbose_name_plural': 'tipos de rampla',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'tipo de servicio',
                'verbose_name_plural': 'tipos de servicio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoTarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'tipo de tarifa',
                'verbose_name_plural': 'tipos de tarifa',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True, verbose_name='dirección')),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locales', to='maestros.cliente')),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locales', to='maestros.comuna')),
            ],
            options={
                'verbose_name': 'local',
                'verbose_name_plural': 'locales',
                'ordering': ['cliente__razon_social', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunas', to='maestros.region', verbose_name='región'),
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometros', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('comuna_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_destino', to='maestros.comuna', verbose_name='comuna destino')),
                ('comuna_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_origen', to='maestros.comuna', verbose_name='comuna origen')),
            ],
            options={
                'verbose_name': 'ruta',
                'verbose_name_plural': 'rutas',
                'ordering': ['comuna_origen__nombre', 'comuna_destino__nombre'],
                'unique_together': {('comuna_origen', 'comuna_destino')},
            },
        ),
        migrations.CreateModel(
            name='Rampla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=20, unique=True)),
                ('es_externa', models.BooleanField(default=False, help_text='Rampla de un proveedor externo, no propia de la flota.', verbose_name='es externa')),
                ('activa', models.BooleanField(default=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('proveedor', models.ForeignKey(blank=True, help_text='Solo si la rampla es externa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ramplas', to='maestros.proveedor')),
                ('tipo_rampla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ramplas', to='maestros.tiporampla', verbose_name='tipo de rampla')),
            ],
            options={
                'verbose_name': 'rampla',
                'verbose_name_plural': 'ramplas',
                'ordering': ['patente'],
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('vigente_desde', models.DateField(blank=True, null=True)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='maestros.cliente')),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarifas', to='maestros.local')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifas', to='maestros.ruta')),
                ('tipo_tarifa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifas', to='maestros.tipotarifa', verbose_name='tipo de tarifa')),
            ],
            options={
                'verbose_name': 'tarifa',
                'verbose_name_plural': 'tarifas',
                'ordering': ['cliente__razon_social', 'ruta'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='comuna',
            unique_together={('nombre', 'region')},
        ),
    ]
