# Generated by Django 5.1.4 on 2026-08-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='formato',
            field=models.CharField(blank=True, help_text='Formato de la tienda/local, ej: Líder, Express, SBA, Mayorista, CD.', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo estimado del viaje (flete a proveedor, combustible, etc.) para calcular el profit.', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='valor de venta'),
        ),
    ]
