# Generated by Django 5.1.4 on 2026-08-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0004_local_formato_a_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='condicion_pago',
            field=models.CharField(blank=True, choices=[('Efectivo', 'Efectivo'), ('Cheque', 'Cheque')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo_vendedor',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='es_directo',
            field=models.BooleanField(default=True, help_text='Directo: compra directamente a Transser. Indirecto: a través de un intermediario.', verbose_name='cliente directo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_vendedor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rut_vendedor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
