# Generated by Django 5.1.4 on 2026-08-27 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0005_cliente_condicion_pago_cliente_correo_vendedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'horario de recepción',
                'verbose_name_plural': 'horarios de recepción',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='local',
            name='formato',
        ),
        migrations.AddField(
            model_name='local',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='horario_recepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locales', to='maestros.horariorecepcion'),
        ),
        migrations.DeleteModel(
            name='FormatoLocal',
        ),
    ]
