# Generated by Django 5.1.4 on 2026-08-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0006_horariorecepcion_remove_local_formato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifa',
            name='tipo_tarifa',
        ),
        migrations.RemoveField(
            model_name='tarifa',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='tarifa',
            name='valor',
        ),
        migrations.AddField(
            model_name='tarifa',
            name='congelado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='frio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='frío'),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='seco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='unica',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Para rutas con tarifa plana, sin distinción por tipo de carga.', max_digits=14, null=True, verbose_name='única'),
        ),
        migrations.DeleteModel(
            name='TipoTarifa',
        ),
    ]
