# Generated by Django 5.1.4 on 2026-08-04 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('cliente', models.CharField(max_length=150)),
                ('mandante', models.CharField(blank=True, max_length=150, null=True)),
                ('codigo_local', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_servicio', models.CharField(blank=True, max_length=30, null=True)),
                ('origen', models.CharField(max_length=150)),
                ('destino', models.CharField(max_length=150)),
                ('fecha_carga', models.DateField()),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('tipo_carga', models.CharField(blank=True, max_length=100, null=True)),
                ('conductor_principal', models.CharField(blank=True, max_length=150, null=True)),
                ('conductor_secundario', models.CharField(blank=True, max_length=150, null=True)),
                ('tracto', models.CharField(blank=True, max_length=20, null=True)),
                ('rampla', models.CharField(blank=True, max_length=20, null=True)),
                ('tarifa', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tasa_iva', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_factura', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('Programado', 'Programado'), ('Cargando', 'Cargando'), ('En Ruta', 'En Ruta'), ('Descargando', 'Descargando'), ('Finalizado', 'Finalizado')], default='Programado', max_length=30)),
                ('creado_por', models.CharField(max_length=150)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tarifa_maestra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.tarifamaestra')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EventoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('estado_anterior', models.CharField(blank=True, max_length=30, null=True)),
                ('estado_nuevo', models.CharField(blank=True, max_length=30, null=True)),
                ('rampla_anterior', models.CharField(blank=True, max_length=20, null=True)),
                ('rampla_nueva', models.CharField(blank=True, max_length=20, null=True)),
                ('actor', models.CharField(max_length=150)),
                ('autorizado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('evidencia_foto', models.CharField(blank=True, max_length=500, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='operaciones.servicio')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ComisionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conductor', models.CharField(max_length=150)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('motivo', models.CharField(blank=True, max_length=250, null=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='operaciones.servicio')),
            ],
        ),
    ]
