# Generated by Django 5.1.4 on 2026-10-01 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0007_remove_tarifa_tipo_tarifa_remove_tarifa_costo_and_more'),
        ('operaciones', '0002_remove_servicio_tarifa_maestra_servicio_tarifa_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParadaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_valor_extra', models.BooleanField(default=False, help_text='Un cobro adicional en este local, no una entrega con tarifa de ruta.', verbose_name='valor extra')),
                ('tipo_tarifa', models.CharField(blank=True, choices=[('seco', 'Seco'), ('frio', 'Frío'), ('congelado', 'Congelado'), ('unica', 'Única')], max_length=20, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observacion', models.CharField(blank=True, max_length=250, null=True)),
                ('creado_por', models.CharField(max_length=150)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paradas_servicio', to='maestros.local')),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paradas_servicio', to='maestros.ruta')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='operaciones.servicio')),
                ('tarifa_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paradas_servicio', to='maestros.tarifa')),
            ],
            options={
                'verbose_name': 'parada de servicio',
                'verbose_name_plural': 'paradas de servicio',
                'ordering': ['id'],
            },
        ),
    ]
