# Generated by Django 5.1.4 on 2026-10-01 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0007_remove_tarifa_tipo_tarifa_remove_tarifa_costo_and_more'),
        ('operaciones', '0003_paradaservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='local_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_destino', to='maestros.local'),
        ),
    ]
