# Generated by Django 5.1.4 on 2026-10-02 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_delete_tarifamaestra_remove_conductor_modelo_tracto_and_more'),
        ('maestros', '0007_remove_tarifa_tipo_tarifa_remove_tarifa_costo_and_more'),
        ('operaciones', '0004_servicio_local_destino'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='codigo_local',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='origen',
        ),
        migrations.AddField(
            model_name='servicio',
            name='ruta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='maestros.ruta'),
        ),
        migrations.AlterField(
            model_name='comisionservicio',
            name='conductor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comisiones', to='catalogos.conductor'),
        ),
        migrations.AlterField(
            model_name='eventoservicio',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventoservicio',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_autorizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventoservicio',
            name='rampla_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='maestros.rampla'),
        ),
        migrations.AlterField(
            model_name='eventoservicio',
            name='rampla_nueva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='maestros.rampla'),
        ),
        migrations.AlterField(
            model_name='paradaservicio',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paradas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='maestros.cliente'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='conductor_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_como_principal', to='catalogos.conductor'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='conductor_secundario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_como_secundario', to='catalogos.conductor'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='mandante',
            field=models.ForeignKey(blank=True, help_text='Cliente final cuando el servicio se contrata a través de un intermediario.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios_como_mandante', to='maestros.cliente'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='rampla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='maestros.rampla'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo_carga',
            field=models.CharField(blank=True, choices=[('seco', 'Seco'), ('frio', 'Frío'), ('congelado', 'Congelado'), ('unica', 'Única')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='maestros.tiposervicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tracto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='catalogos.tracto'),
        ),
    ]
