# Generated by Django 5.1.4 on 2026-08-04 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('grupo', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('centro_costo', models.CharField(default='Operaciones', max_length=80)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'categoría de gasto',
                'verbose_name_plural': 'categorías de gasto',
                'ordering': ['grupo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='GastoRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=250)),
                ('proveedor', models.CharField(blank=True, max_length=150, null=True)),
                ('documento_tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('documento_numero', models.CharField(blank=True, max_length=80, null=True)),
                ('monto_neto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('afecto_iva', models.BooleanField(default=True)),
                ('tasa_iva', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('quien_pago', models.CharField(default='Empresa', max_length=50)),
                ('medio_pago', models.CharField(default='Transferencia', max_length=50)),
                ('requiere_rendicion', models.BooleanField(default=False)),
                ('reembolsable', models.BooleanField(default=False)),
                ('evidencia', models.CharField(blank=True, max_length=500, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Revisado', 'Revisado'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Contabilizado', 'Contabilizado')], default='Pendiente', max_length=30)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('creado_por', models.CharField(max_length=150)),
                ('aprobado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gastos.categoriagasto')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='operaciones.servicio')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
