# Generated by Django 5.1.4 on 2026-10-02 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
        ('maestros', '0007_remove_tarifa_tipo_tarifa_remove_tarifa_costo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriagasto',
            name='centro_costo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_gasto', to='maestros.centrocosto'),
        ),
        migrations.AlterField(
            model_name='gastoruta',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gastoruta',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gastoruta',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='maestros.proveedor'),
        ),
    ]
